# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created: Fri Sep 18 17:27:17 2015
#      by: PyQt5 UI code generator 5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(758, 1000)
        font = QtGui.QFont()
        font.setPointSize(9)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("font-size: 9pt;")
        MainWindow.setAnimated(True)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("QTabWidget>QWidget>QWidget{background: white;}")
        self.tabWidget.setObjectName("tabWidget")
        self.setupTab = QtWidgets.QWidget()
        self.setupTab.setObjectName("setupTab")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.setupTab)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.setupTabVerticalLayout = QtWidgets.QVBoxLayout()
        self.setupTabVerticalLayout.setObjectName("setupTabVerticalLayout")
        self.setupSessionArduinoLayout = QtWidgets.QGridLayout()
        self.setupSessionArduinoLayout.setObjectName("setupSessionArduinoLayout")
        self.arduino_GroupBox = QtWidgets.QGroupBox(self.setupTab)
        self.arduino_GroupBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.arduino_GroupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.arduino_GroupBox.setFlat(False)
        self.arduino_GroupBox.setObjectName("arduino_GroupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.arduino_GroupBox)
        self.verticalLayout_3.setSpacing(-1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.device_ComboBox = QtWidgets.QComboBox(self.arduino_GroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.device_ComboBox.sizePolicy().hasHeightForWidth())
        self.device_ComboBox.setSizePolicy(sizePolicy)
        self.device_ComboBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.device_ComboBox.setObjectName("device_ComboBox")
        self.gridLayout_5.addWidget(self.device_ComboBox, 0, 1, 1, 1)
        self.baudRate_ComboBox = QtWidgets.QComboBox(self.arduino_GroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.baudRate_ComboBox.sizePolicy().hasHeightForWidth())
        self.baudRate_ComboBox.setSizePolicy(sizePolicy)
        self.baudRate_ComboBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.baudRate_ComboBox.setObjectName("baudRate_ComboBox")
        self.baudRate_ComboBox.addItem("")
        self.gridLayout_5.addWidget(self.baudRate_ComboBox, 1, 1, 1, 1)
        self.baudRateLabel = QtWidgets.QLabel(self.arduino_GroupBox)
        self.baudRateLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.baudRateLabel.setObjectName("baudRateLabel")
        self.gridLayout_5.addWidget(self.baudRateLabel, 1, 0, 1, 1)
        self.deviceLabel = QtWidgets.QLabel(self.arduino_GroupBox)
        self.deviceLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.deviceLabel.setObjectName("deviceLabel")
        self.gridLayout_5.addWidget(self.deviceLabel, 0, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_5)
        self.arduinoConnectedText_Label = QtWidgets.QLabel(self.arduino_GroupBox)
        self.arduinoConnectedText_Label.setStyleSheet("color:rgb(255, 0, 100)")
        self.arduinoConnectedText_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.arduinoConnectedText_Label.setObjectName("arduinoConnectedText_Label")
        self.verticalLayout_3.addWidget(self.arduinoConnectedText_Label)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.testStimNum_SpinBox = QtWidgets.QSpinBox(self.arduino_GroupBox)
        self.testStimNum_SpinBox.setMinimum(1)
        self.testStimNum_SpinBox.setObjectName("testStimNum_SpinBox")
        self.gridLayout_6.addWidget(self.testStimNum_SpinBox, 0, 1, 1, 1)
        self.testReward_Button = QtWidgets.QPushButton(self.arduino_GroupBox)
        self.testReward_Button.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.testReward_Button.sizePolicy().hasHeightForWidth())
        self.testReward_Button.setSizePolicy(sizePolicy)
        self.testReward_Button.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.testReward_Button.setObjectName("testReward_Button")
        self.gridLayout_6.addWidget(self.testReward_Button, 1, 0, 1, 1)
        self.testRewardNum_SpinBox = QtWidgets.QSpinBox(self.arduino_GroupBox)
        self.testRewardNum_SpinBox.setMinimum(1)
        self.testRewardNum_SpinBox.setObjectName("testRewardNum_SpinBox")
        self.gridLayout_6.addWidget(self.testRewardNum_SpinBox, 1, 1, 1, 1)
        self.testStim_Button = QtWidgets.QPushButton(self.arduino_GroupBox)
        self.testStim_Button.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.testStim_Button.sizePolicy().hasHeightForWidth())
        self.testStim_Button.setSizePolicy(sizePolicy)
        self.testStim_Button.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.testStim_Button.setObjectName("testStim_Button")
        self.gridLayout_6.addWidget(self.testStim_Button, 0, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_6)
        self.setupSessionArduinoLayout.addWidget(self.arduino_GroupBox, 0, 1, 1, 1)
        self.session_GroupBox = QtWidgets.QGroupBox(self.setupTab)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.session_GroupBox.setFont(font)
        self.session_GroupBox.setFlat(False)
        self.session_GroupBox.setObjectName("session_GroupBox")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.session_GroupBox)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.numberOfTrialsLabel = QtWidgets.QLabel(self.session_GroupBox)
        self.numberOfTrialsLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.numberOfTrialsLabel.setObjectName("numberOfTrialsLabel")
        self.gridLayout_4.addWidget(self.numberOfTrialsLabel, 2, 0, 1, 1)
        self.weightLabel = QtWidgets.QLabel(self.session_GroupBox)
        self.weightLabel.setTextFormat(QtCore.Qt.AutoText)
        self.weightLabel.setScaledContents(False)
        self.weightLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.weightLabel.setContentsMargins(0, 0, 0, 0)
        self.weightLabel.setIndent(-1)
        self.weightLabel.setObjectName("weightLabel")
        self.gridLayout_4.addWidget(self.weightLabel, 1, 0, 1, 1)
        self.mouseIDLabel = QtWidgets.QLabel(self.session_GroupBox)
        self.mouseIDLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.mouseIDLabel.setObjectName("mouseIDLabel")
        self.gridLayout_4.addWidget(self.mouseIDLabel, 0, 0, 1, 1)
        self.weight_SpinBox = QtWidgets.QDoubleSpinBox(self.session_GroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.weight_SpinBox.sizePolicy().hasHeightForWidth())
        self.weight_SpinBox.setSizePolicy(sizePolicy)
        self.weight_SpinBox.setSingleStep(0.1)
        self.weight_SpinBox.setObjectName("weight_SpinBox")
        self.gridLayout_4.addWidget(self.weight_SpinBox, 1, 1, 1, 1)
        self.subjectID_LineEdit = QtWidgets.QLineEdit(self.session_GroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.subjectID_LineEdit.sizePolicy().hasHeightForWidth())
        self.subjectID_LineEdit.setSizePolicy(sizePolicy)
        self.subjectID_LineEdit.setInputMask("")
        self.subjectID_LineEdit.setText("")
        self.subjectID_LineEdit.setObjectName("subjectID_LineEdit")
        self.gridLayout_4.addWidget(self.subjectID_LineEdit, 0, 1, 1, 1)
        self.loadPreset_ComboBox = QtWidgets.QComboBox(self.session_GroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadPreset_ComboBox.sizePolicy().hasHeightForWidth())
        self.loadPreset_ComboBox.setSizePolicy(sizePolicy)
        self.loadPreset_ComboBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.loadPreset_ComboBox.setObjectName("loadPreset_ComboBox")
        self.loadPreset_ComboBox.addItem("")
        self.gridLayout_4.addWidget(self.loadPreset_ComboBox, 3, 1, 1, 1)
        self.loadPresetLabel = QtWidgets.QLabel(self.session_GroupBox)
        self.loadPresetLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.loadPresetLabel.setObjectName("loadPresetLabel")
        self.gridLayout_4.addWidget(self.loadPresetLabel, 3, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.sessionDuration_SpinBox = QtWidgets.QSpinBox(self.session_GroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sessionDuration_SpinBox.sizePolicy().hasHeightForWidth())
        self.sessionDuration_SpinBox.setSizePolicy(sizePolicy)
        self.sessionDuration_SpinBox.setMinimum(1)
        self.sessionDuration_SpinBox.setMaximum(1000)
        self.sessionDuration_SpinBox.setObjectName("sessionDuration_SpinBox")
        self.gridLayout.addWidget(self.sessionDuration_SpinBox, 0, 0, 1, 1)
        self.sessionDurationMode_ComboBox = QtWidgets.QComboBox(self.session_GroupBox)
        self.sessionDurationMode_ComboBox.setObjectName("sessionDurationMode_ComboBox")
        self.sessionDurationMode_ComboBox.addItem("")
        self.sessionDurationMode_ComboBox.addItem("")
        self.gridLayout.addWidget(self.sessionDurationMode_ComboBox, 0, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout, 2, 1, 1, 1)
        self.horizontalLayout_13.addLayout(self.gridLayout_4)
        self.setupSessionArduinoLayout.addWidget(self.session_GroupBox, 0, 0, 1, 1)
        self.setupTabVerticalLayout.addLayout(self.setupSessionArduinoLayout)
        self.trial_GroupBox = QtWidgets.QGroupBox(self.setupTab)
        self.trial_GroupBox.setStyleSheet("background-color: none;")
        self.trial_GroupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.trial_GroupBox.setFlat(False)
        self.trial_GroupBox.setCheckable(False)
        self.trial_GroupBox.setChecked(False)
        self.trial_GroupBox.setObjectName("trial_GroupBox")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.trial_GroupBox)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.scrollArea = QtWidgets.QScrollArea(self.trial_GroupBox)
        self.scrollArea.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.scrollArea.setFont(font)
        self.scrollArea.setStyleSheet("QScrollArea>QWidget>QWidget {\n"
"background-color: white;\n"
"}\n"
"\n"
"QScrollArea>QWidget>QScrollBar {\n"
"background-color: none;\n"
"}")
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 639, 865))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_3 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout_12 = QtWidgets.QGridLayout()
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        self.label_11.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setMinimumSize(QtCore.QSize(100, 0))
        self.label_11.setObjectName("label_11")
        self.gridLayout_12.addWidget(self.label_11, 0, 0, 1, 1)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.checkBox_3 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_3.setEnabled(False)
        self.checkBox_3.setText("")
        self.checkBox_3.setObjectName("checkBox_3")
        self.horizontalLayout_23.addWidget(self.checkBox_3)
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.doubleSpinBox_2.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_2.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_2.setSizePolicy(sizePolicy)
        self.doubleSpinBox_2.setDecimals(0)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.horizontalLayout_23.addWidget(self.doubleSpinBox_2)
        self.gridLayout_12.addLayout(self.horizontalLayout_23, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_12.addWidget(self.label_2, 1, 0, 1, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.witholdBeforeStim_CheckBox = QtWidgets.QCheckBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.witholdBeforeStim_CheckBox.sizePolicy().hasHeightForWidth())
        self.witholdBeforeStim_CheckBox.setSizePolicy(sizePolicy)
        self.witholdBeforeStim_CheckBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.witholdBeforeStim_CheckBox.setText("")
        self.witholdBeforeStim_CheckBox.setObjectName("witholdBeforeStim_CheckBox")
        self.horizontalLayout_10.addWidget(self.witholdBeforeStim_CheckBox)
        self.witholdBeforeStimMin_SpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.witholdBeforeStimMin_SpinBox.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.witholdBeforeStimMin_SpinBox.sizePolicy().hasHeightForWidth())
        self.witholdBeforeStimMin_SpinBox.setSizePolicy(sizePolicy)
        self.witholdBeforeStimMin_SpinBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.witholdBeforeStimMin_SpinBox.setObjectName("witholdBeforeStimMin_SpinBox")
        self.horizontalLayout_10.addWidget(self.witholdBeforeStimMin_SpinBox)
        self.witholdBeforeStimMax_SpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.witholdBeforeStimMax_SpinBox.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.witholdBeforeStimMax_SpinBox.sizePolicy().hasHeightForWidth())
        self.witholdBeforeStimMax_SpinBox.setSizePolicy(sizePolicy)
        self.witholdBeforeStimMax_SpinBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.witholdBeforeStimMax_SpinBox.setObjectName("witholdBeforeStimMax_SpinBox")
        self.horizontalLayout_10.addWidget(self.witholdBeforeStimMax_SpinBox)
        self.gridLayout_12.addLayout(self.horizontalLayout_10, 1, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_12, 0, 0, 1, 1)
        self.horizontalLayout_18.addLayout(self.gridLayout_2)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox_5 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_22.setContentsMargins(-1, 12, -1, -1)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setSpacing(-1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_16 = QtWidgets.QLabel(self.groupBox_5)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 5, 0, 1, 1)
        self.reportChannelsLabel = QtWidgets.QLabel(self.groupBox_5)
        self.reportChannelsLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.reportChannelsLabel.setObjectName("reportChannelsLabel")
        self.gridLayout_3.addWidget(self.reportChannelsLabel, 2, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.stimLength_SpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.stimLength_SpinBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.stimLength_SpinBox.setSingleStep(0.5)
        self.stimLength_SpinBox.setObjectName("stimLength_SpinBox")
        self.horizontalLayout_4.addWidget(self.stimLength_SpinBox)
        self.respStopsStim_CheckBox = QtWidgets.QCheckBox(self.groupBox_5)
        self.respStopsStim_CheckBox.setObjectName("respStopsStim_CheckBox")
        self.horizontalLayout_4.addWidget(self.respStopsStim_CheckBox)
        self.gridLayout_3.addLayout(self.horizontalLayout_4, 16, 1, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.autoReward_CheckBox = QtWidgets.QCheckBox(self.groupBox_5)
        self.autoReward_CheckBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.autoReward_CheckBox.setText("")
        self.autoReward_CheckBox.setObjectName("autoReward_CheckBox")
        self.horizontalLayout_5.addWidget(self.autoReward_CheckBox)
        self.autoRewardDelay_SpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.autoRewardDelay_SpinBox.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.autoRewardDelay_SpinBox.sizePolicy().hasHeightForWidth())
        self.autoRewardDelay_SpinBox.setSizePolicy(sizePolicy)
        self.autoRewardDelay_SpinBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.autoRewardDelay_SpinBox.setSingleStep(0.1)
        self.autoRewardDelay_SpinBox.setObjectName("autoRewardDelay_SpinBox")
        self.horizontalLayout_5.addWidget(self.autoRewardDelay_SpinBox)
        self.gridLayout_3.addLayout(self.horizontalLayout_5, 21, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox_5)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 19, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.rewardRemoval_checkBox = QtWidgets.QCheckBox(self.groupBox_5)
        self.rewardRemoval_checkBox.setText("")
        self.rewardRemoval_checkBox.setObjectName("rewardRemoval_checkBox")
        self.horizontalLayout_8.addWidget(self.rewardRemoval_checkBox)
        self.rewardRemovalDelay_SpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rewardRemovalDelay_SpinBox.sizePolicy().hasHeightForWidth())
        self.rewardRemovalDelay_SpinBox.setSizePolicy(sizePolicy)
        self.rewardRemovalDelay_SpinBox.setDecimals(2)
        self.rewardRemovalDelay_SpinBox.setSingleStep(0.1)
        self.rewardRemovalDelay_SpinBox.setObjectName("rewardRemovalDelay_SpinBox")
        self.horizontalLayout_8.addWidget(self.rewardRemovalDelay_SpinBox)
        self.gridLayout_3.addLayout(self.horizontalLayout_8, 5, 1, 1, 1)
        self.stimOrderLabel = QtWidgets.QLabel(self.groupBox_5)
        self.stimOrderLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.stimOrderLabel.setObjectName("stimOrderLabel")
        self.gridLayout_3.addWidget(self.stimOrderLabel, 6, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_5)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 14, 0, 1, 1)
        self.cueToStimDelay_SpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.cueToStimDelay_SpinBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.cueToStimDelay_SpinBox.setSingleStep(0.5)
        self.cueToStimDelay_SpinBox.setObjectName("cueToStimDelay_SpinBox")
        self.gridLayout_3.addWidget(self.cueToStimDelay_SpinBox, 14, 1, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.cueTrial_CheckBox = QtWidgets.QCheckBox(self.groupBox_5)
        self.cueTrial_CheckBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.cueTrial_CheckBox.setObjectName("cueTrial_CheckBox")
        self.horizontalLayout_9.addWidget(self.cueTrial_CheckBox)
        self.cueStim_CheckBox = QtWidgets.QCheckBox(self.groupBox_5)
        self.cueStim_CheckBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.cueStim_CheckBox.setObjectName("cueStim_CheckBox")
        self.horizontalLayout_9.addWidget(self.cueStim_CheckBox)
        self.cueResponse_CheckBox = QtWidgets.QCheckBox(self.groupBox_5)
        self.cueResponse_CheckBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.cueResponse_CheckBox.setObjectName("cueResponse_CheckBox")
        self.horizontalLayout_9.addWidget(self.cueResponse_CheckBox)
        self.gridLayout_3.addLayout(self.horizontalLayout_9, 11, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.response1_CheckBox = QtWidgets.QCheckBox(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.response1_CheckBox.sizePolicy().hasHeightForWidth())
        self.response1_CheckBox.setSizePolicy(sizePolicy)
        self.response1_CheckBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.response1_CheckBox.setObjectName("response1_CheckBox")
        self.horizontalLayout_2.addWidget(self.response1_CheckBox)
        self.response2_CheckBox = QtWidgets.QCheckBox(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.response2_CheckBox.sizePolicy().hasHeightForWidth())
        self.response2_CheckBox.setSizePolicy(sizePolicy)
        self.response2_CheckBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.response2_CheckBox.setObjectName("response2_CheckBox")
        self.horizontalLayout_2.addWidget(self.response2_CheckBox)
        self.response3_CheckBox = QtWidgets.QCheckBox(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.response3_CheckBox.sizePolicy().hasHeightForWidth())
        self.response3_CheckBox.setSizePolicy(sizePolicy)
        self.response3_CheckBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.response3_CheckBox.setObjectName("response3_CheckBox")
        self.horizontalLayout_2.addWidget(self.response3_CheckBox)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 2, 1, 1, 1)
        self.firstStimLabel = QtWidgets.QLabel(self.groupBox_5)
        self.firstStimLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.firstStimLabel.setObjectName("firstStimLabel")
        self.gridLayout_3.addWidget(self.firstStimLabel, 7, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.stimOrder_ComboBox = QtWidgets.QComboBox(self.groupBox_5)
        self.stimOrder_ComboBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.stimOrder_ComboBox.setObjectName("stimOrder_ComboBox")
        self.stimOrder_ComboBox.addItem("")
        self.stimOrder_ComboBox.addItem("")
        self.stimOrder_ComboBox.addItem("")
        self.horizontalLayout_3.addWidget(self.stimOrder_ComboBox)
        self.stimOrderGroupSize_SpinBox = QtWidgets.QSpinBox(self.groupBox_5)
        self.stimOrderGroupSize_SpinBox.setSuffix("")
        self.stimOrderGroupSize_SpinBox.setObjectName("stimOrderGroupSize_SpinBox")
        self.horizontalLayout_3.addWidget(self.stimOrderGroupSize_SpinBox)
        self.gridLayout_3.addLayout(self.horizontalLayout_3, 6, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox_5)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 22, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_5)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 21, 0, 1, 1)
        self.endOfTrialDelay_SpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.endOfTrialDelay_SpinBox.setSingleStep(0.5)
        self.endOfTrialDelay_SpinBox.setObjectName("endOfTrialDelay_SpinBox")
        self.gridLayout_3.addWidget(self.endOfTrialDelay_SpinBox, 19, 1, 1, 1)
        self.postStimDelay_SpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.postStimDelay_SpinBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.postStimDelay_SpinBox.setSingleStep(0.1)
        self.postStimDelay_SpinBox.setObjectName("postStimDelay_SpinBox")
        self.gridLayout_3.addWidget(self.postStimDelay_SpinBox, 17, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_5)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 17, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_5)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 16, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.groupBox_5)
        self.label_20.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName("label_20")
        self.gridLayout_3.addWidget(self.label_20, 3, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_5)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 18, 0, 1, 1)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.repeatIfIncorrect_CheckBox = QtWidgets.QCheckBox(self.groupBox_5)
        self.repeatIfIncorrect_CheckBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.repeatIfIncorrect_CheckBox.setText("")
        self.repeatIfIncorrect_CheckBox.setObjectName("repeatIfIncorrect_CheckBox")
        self.horizontalLayout_17.addWidget(self.repeatIfIncorrect_CheckBox)
        self.gridLayout_3.addLayout(self.horizontalLayout_17, 8, 1, 1, 1)
        self.firstStim_ComboBox = QtWidgets.QComboBox(self.groupBox_5)
        self.firstStim_ComboBox.setMouseTracking(False)
        self.firstStim_ComboBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.firstStim_ComboBox.setObjectName("firstStim_ComboBox")
        self.firstStim_ComboBox.addItem("")
        self.gridLayout_3.addWidget(self.firstStim_ComboBox, 7, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_5)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 8, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.checkBox = QtWidgets.QCheckBox(self.groupBox_5)
        self.checkBox.setEnabled(False)
        self.checkBox.setText("")
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_6.addWidget(self.checkBox)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.doubleSpinBox.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox.setSizePolicy(sizePolicy)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.horizontalLayout_6.addWidget(self.doubleSpinBox)
        self.spinBox_2 = QtWidgets.QSpinBox(self.groupBox_5)
        self.spinBox_2.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_2.sizePolicy().hasHeightForWidth())
        self.spinBox_2.setSizePolicy(sizePolicy)
        self.spinBox_2.setSuffix("")
        self.spinBox_2.setObjectName("spinBox_2")
        self.horizontalLayout_6.addWidget(self.spinBox_2)
        self.comboBox = QtWidgets.QComboBox(self.groupBox_5)
        self.comboBox.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_6.addWidget(self.comboBox)
        self.spinBox = QtWidgets.QSpinBox(self.groupBox_5)
        self.spinBox.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox.sizePolicy().hasHeightForWidth())
        self.spinBox.setSizePolicy(sizePolicy)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout_6.addWidget(self.spinBox)
        self.gridLayout_3.addLayout(self.horizontalLayout_6, 22, 1, 1, 1)
        self.responseWindow_SpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.responseWindow_SpinBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.responseWindow_SpinBox.setSingleStep(0.5)
        self.responseWindow_SpinBox.setObjectName("responseWindow_SpinBox")
        self.gridLayout_3.addWidget(self.responseWindow_SpinBox, 18, 1, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.groupBox_5)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_3.addWidget(self.line_4, 24, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_5)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 25, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_5)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 9, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_5)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 11, 0, 1, 1)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_12 = QtWidgets.QLabel(self.groupBox_5)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_7.addWidget(self.label_12, 0, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_5)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_7.addWidget(self.label_13, 2, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.groupBox_5)
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout_7.addWidget(self.label_18, 1, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_7, 4, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.groupBox_5)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_3.addWidget(self.line_2, 26, 1, 1, 1)
        self.line = QtWidgets.QFrame(self.groupBox_5)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_3.addWidget(self.line, 10, 1, 1, 1)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.punish_CheckBox = QtWidgets.QCheckBox(self.groupBox_5)
        self.punish_CheckBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.punish_CheckBox.setText("")
        self.punish_CheckBox.setObjectName("punish_CheckBox")
        self.horizontalLayout_12.addWidget(self.punish_CheckBox)
        self.punishType_ComboBox = QtWidgets.QComboBox(self.groupBox_5)
        self.punishType_ComboBox.setEnabled(False)
        self.punishType_ComboBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.punishType_ComboBox.setObjectName("punishType_ComboBox")
        self.punishType_ComboBox.addItem("")
        self.punishType_ComboBox.addItem("")
        self.horizontalLayout_12.addWidget(self.punishType_ComboBox)
        self.punishLength_SpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.punishLength_SpinBox.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.punishLength_SpinBox.sizePolicy().hasHeightForWidth())
        self.punishLength_SpinBox.setSizePolicy(sizePolicy)
        self.punishLength_SpinBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.punishLength_SpinBox.setSingleStep(0.5)
        self.punishLength_SpinBox.setObjectName("punishLength_SpinBox")
        self.horizontalLayout_12.addWidget(self.punishLength_SpinBox)
        self.gridLayout_3.addLayout(self.horizontalLayout_12, 25, 1, 1, 1)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.reward1_CheckBox = QtWidgets.QCheckBox(self.groupBox_5)
        self.reward1_CheckBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.reward1_CheckBox.setObjectName("reward1_CheckBox")
        self.horizontalLayout_16.addWidget(self.reward1_CheckBox)
        self.reward2_CheckBox = QtWidgets.QCheckBox(self.groupBox_5)
        self.reward2_CheckBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.reward2_CheckBox.setObjectName("reward2_CheckBox")
        self.horizontalLayout_16.addWidget(self.reward2_CheckBox)
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox_5)
        self.checkBox_2.setObjectName("checkBox_2")
        self.horizontalLayout_16.addWidget(self.checkBox_2)
        self.gridLayout_3.addLayout(self.horizontalLayout_16, 3, 1, 1, 1)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.autoTransition_CheckBox = QtWidgets.QCheckBox(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.autoTransition_CheckBox.sizePolicy().hasHeightForWidth())
        self.autoTransition_CheckBox.setSizePolicy(sizePolicy)
        self.autoTransition_CheckBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.autoTransition_CheckBox.setText("")
        self.autoTransition_CheckBox.setObjectName("autoTransition_CheckBox")
        self.horizontalLayout_14.addWidget(self.autoTransition_CheckBox)
        self.autoTransitionTo_ComboBox = QtWidgets.QComboBox(self.groupBox_5)
        self.autoTransitionTo_ComboBox.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.autoTransitionTo_ComboBox.sizePolicy().hasHeightForWidth())
        self.autoTransitionTo_ComboBox.setSizePolicy(sizePolicy)
        self.autoTransitionTo_ComboBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.autoTransitionTo_ComboBox.setObjectName("autoTransitionTo_ComboBox")
        self.autoTransitionTo_ComboBox.addItem("")
        self.horizontalLayout_14.addWidget(self.autoTransitionTo_ComboBox)
        self.autoTransitionAfterNum_SpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.autoTransitionAfterNum_SpinBox.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.autoTransitionAfterNum_SpinBox.sizePolicy().hasHeightForWidth())
        self.autoTransitionAfterNum_SpinBox.setSizePolicy(sizePolicy)
        self.autoTransitionAfterNum_SpinBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.autoTransitionAfterNum_SpinBox.setObjectName("autoTransitionAfterNum_SpinBox")
        self.horizontalLayout_14.addWidget(self.autoTransitionAfterNum_SpinBox)
        self.autoTransitionAfterCriteria_ComboBox = QtWidgets.QComboBox(self.groupBox_5)
        self.autoTransitionAfterCriteria_ComboBox.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.autoTransitionAfterCriteria_ComboBox.sizePolicy().hasHeightForWidth())
        self.autoTransitionAfterCriteria_ComboBox.setSizePolicy(sizePolicy)
        self.autoTransitionAfterCriteria_ComboBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.autoTransitionAfterCriteria_ComboBox.setObjectName("autoTransitionAfterCriteria_ComboBox")
        self.autoTransitionAfterCriteria_ComboBox.addItem("")
        self.autoTransitionAfterCriteria_ComboBox.addItem("")
        self.autoTransitionAfterCriteria_ComboBox.addItem("")
        self.autoTransitionAfterCriteria_ComboBox.addItem("")
        self.horizontalLayout_14.addWidget(self.autoTransitionAfterCriteria_ComboBox)
        self.autoTransitionFor_SpinBox = QtWidgets.QSpinBox(self.groupBox_5)
        self.autoTransitionFor_SpinBox.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.autoTransitionFor_SpinBox.sizePolicy().hasHeightForWidth())
        self.autoTransitionFor_SpinBox.setSizePolicy(sizePolicy)
        self.autoTransitionFor_SpinBox.setObjectName("autoTransitionFor_SpinBox")
        self.horizontalLayout_14.addWidget(self.autoTransitionFor_SpinBox)
        self.gridLayout_3.addLayout(self.horizontalLayout_14, 9, 1, 1, 1)
        self.widget = QtWidgets.QWidget(self.groupBox_5)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setSpacing(5)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.respReq8_SpinBox = QtWidgets.QSpinBox(self.widget)
        self.respReq8_SpinBox.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.respReq8_SpinBox.sizePolicy().hasHeightForWidth())
        self.respReq8_SpinBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.respReq8_SpinBox.setFont(font)
        self.respReq8_SpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.respReq8_SpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.respReq8_SpinBox.setObjectName("respReq8_SpinBox")
        self.gridLayout_10.addWidget(self.respReq8_SpinBox, 2, 7, 1, 1)
        self.respReq4_SpinBox = QtWidgets.QSpinBox(self.widget)
        self.respReq4_SpinBox.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.respReq4_SpinBox.sizePolicy().hasHeightForWidth())
        self.respReq4_SpinBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.respReq4_SpinBox.setFont(font)
        self.respReq4_SpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.respReq4_SpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.respReq4_SpinBox.setObjectName("respReq4_SpinBox")
        self.gridLayout_10.addWidget(self.respReq4_SpinBox, 2, 3, 1, 1)
        self.respReq5_SpinBox = QtWidgets.QSpinBox(self.widget)
        self.respReq5_SpinBox.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.respReq5_SpinBox.sizePolicy().hasHeightForWidth())
        self.respReq5_SpinBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.respReq5_SpinBox.setFont(font)
        self.respReq5_SpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.respReq5_SpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.respReq5_SpinBox.setObjectName("respReq5_SpinBox")
        self.gridLayout_10.addWidget(self.respReq5_SpinBox, 2, 4, 1, 1)
        self.stim2_CheckBox = QtWidgets.QCheckBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stim2_CheckBox.sizePolicy().hasHeightForWidth())
        self.stim2_CheckBox.setSizePolicy(sizePolicy)
        self.stim2_CheckBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.stim2_CheckBox.setObjectName("stim2_CheckBox")
        self.gridLayout_10.addWidget(self.stim2_CheckBox, 0, 1, 1, 1)
        self.respReq3_SpinBox = QtWidgets.QSpinBox(self.widget)
        self.respReq3_SpinBox.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.respReq3_SpinBox.sizePolicy().hasHeightForWidth())
        self.respReq3_SpinBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.respReq3_SpinBox.setFont(font)
        self.respReq3_SpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.respReq3_SpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.respReq3_SpinBox.setObjectName("respReq3_SpinBox")
        self.gridLayout_10.addWidget(self.respReq3_SpinBox, 2, 2, 1, 1)
        self.stim8_CheckBox = QtWidgets.QCheckBox(self.widget)
        self.stim8_CheckBox.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stim8_CheckBox.sizePolicy().hasHeightForWidth())
        self.stim8_CheckBox.setSizePolicy(sizePolicy)
        self.stim8_CheckBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.stim8_CheckBox.setObjectName("stim8_CheckBox")
        self.gridLayout_10.addWidget(self.stim8_CheckBox, 0, 7, 1, 1)
        self.stim3_CheckBox = QtWidgets.QCheckBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stim3_CheckBox.sizePolicy().hasHeightForWidth())
        self.stim3_CheckBox.setSizePolicy(sizePolicy)
        self.stim3_CheckBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.stim3_CheckBox.setObjectName("stim3_CheckBox")
        self.gridLayout_10.addWidget(self.stim3_CheckBox, 0, 2, 1, 1)
        self.stim6_CheckBox = QtWidgets.QCheckBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stim6_CheckBox.sizePolicy().hasHeightForWidth())
        self.stim6_CheckBox.setSizePolicy(sizePolicy)
        self.stim6_CheckBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.stim6_CheckBox.setObjectName("stim6_CheckBox")
        self.gridLayout_10.addWidget(self.stim6_CheckBox, 0, 5, 1, 1)
        self.stim1_CheckBox = QtWidgets.QCheckBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stim1_CheckBox.sizePolicy().hasHeightForWidth())
        self.stim1_CheckBox.setSizePolicy(sizePolicy)
        self.stim1_CheckBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.stim1_CheckBox.setObjectName("stim1_CheckBox")
        self.gridLayout_10.addWidget(self.stim1_CheckBox, 0, 0, 1, 1)
        self.stim4_CheckBox = QtWidgets.QCheckBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stim4_CheckBox.sizePolicy().hasHeightForWidth())
        self.stim4_CheckBox.setSizePolicy(sizePolicy)
        self.stim4_CheckBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.stim4_CheckBox.setObjectName("stim4_CheckBox")
        self.gridLayout_10.addWidget(self.stim4_CheckBox, 0, 3, 1, 1)
        self.respReq2_SpinBox = QtWidgets.QSpinBox(self.widget)
        self.respReq2_SpinBox.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.respReq2_SpinBox.sizePolicy().hasHeightForWidth())
        self.respReq2_SpinBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.respReq2_SpinBox.setFont(font)
        self.respReq2_SpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.respReq2_SpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.respReq2_SpinBox.setObjectName("respReq2_SpinBox")
        self.gridLayout_10.addWidget(self.respReq2_SpinBox, 2, 1, 1, 1)
        self.stim7_CheckBox = QtWidgets.QCheckBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stim7_CheckBox.sizePolicy().hasHeightForWidth())
        self.stim7_CheckBox.setSizePolicy(sizePolicy)
        self.stim7_CheckBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.stim7_CheckBox.setObjectName("stim7_CheckBox")
        self.gridLayout_10.addWidget(self.stim7_CheckBox, 0, 6, 1, 1)
        self.respReq7_SpinBox = QtWidgets.QSpinBox(self.widget)
        self.respReq7_SpinBox.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.respReq7_SpinBox.sizePolicy().hasHeightForWidth())
        self.respReq7_SpinBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.respReq7_SpinBox.setFont(font)
        self.respReq7_SpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.respReq7_SpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.respReq7_SpinBox.setObjectName("respReq7_SpinBox")
        self.gridLayout_10.addWidget(self.respReq7_SpinBox, 2, 6, 1, 1)
        self.stim5_CheckBox = QtWidgets.QCheckBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stim5_CheckBox.sizePolicy().hasHeightForWidth())
        self.stim5_CheckBox.setSizePolicy(sizePolicy)
        self.stim5_CheckBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.stim5_CheckBox.setObjectName("stim5_CheckBox")
        self.gridLayout_10.addWidget(self.stim5_CheckBox, 0, 4, 1, 1)
        self.respReq6_SpinBox = QtWidgets.QSpinBox(self.widget)
        self.respReq6_SpinBox.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.respReq6_SpinBox.sizePolicy().hasHeightForWidth())
        self.respReq6_SpinBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.respReq6_SpinBox.setFont(font)
        self.respReq6_SpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.respReq6_SpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.respReq6_SpinBox.setObjectName("respReq6_SpinBox")
        self.gridLayout_10.addWidget(self.respReq6_SpinBox, 2, 5, 1, 1)
        self.rewardedChan5_SpinBox = QtWidgets.QSpinBox(self.widget)
        self.rewardedChan5_SpinBox.setEnabled(False)
        self.rewardedChan5_SpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.rewardedChan5_SpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.rewardedChan5_SpinBox.setObjectName("rewardedChan5_SpinBox")
        self.gridLayout_10.addWidget(self.rewardedChan5_SpinBox, 3, 4, 1, 1)
        self.respReq1_SpinBox = QtWidgets.QSpinBox(self.widget)
        self.respReq1_SpinBox.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.respReq1_SpinBox.sizePolicy().hasHeightForWidth())
        self.respReq1_SpinBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.respReq1_SpinBox.setFont(font)
        self.respReq1_SpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.respReq1_SpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.respReq1_SpinBox.setObjectName("respReq1_SpinBox")
        self.gridLayout_10.addWidget(self.respReq1_SpinBox, 2, 0, 1, 1)
        self.rewardedChan2_SpinBox = QtWidgets.QSpinBox(self.widget)
        self.rewardedChan2_SpinBox.setEnabled(False)
        self.rewardedChan2_SpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.rewardedChan2_SpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.rewardedChan2_SpinBox.setObjectName("rewardedChan2_SpinBox")
        self.gridLayout_10.addWidget(self.rewardedChan2_SpinBox, 3, 1, 1, 1)
        self.rewardedChan4_SpinBox = QtWidgets.QSpinBox(self.widget)
        self.rewardedChan4_SpinBox.setEnabled(False)
        self.rewardedChan4_SpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.rewardedChan4_SpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.rewardedChan4_SpinBox.setObjectName("rewardedChan4_SpinBox")
        self.gridLayout_10.addWidget(self.rewardedChan4_SpinBox, 3, 3, 1, 1)
        self.rewardedChan3_SpinBox = QtWidgets.QSpinBox(self.widget)
        self.rewardedChan3_SpinBox.setEnabled(False)
        self.rewardedChan3_SpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.rewardedChan3_SpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.rewardedChan3_SpinBox.setObjectName("rewardedChan3_SpinBox")
        self.gridLayout_10.addWidget(self.rewardedChan3_SpinBox, 3, 2, 1, 1)
        self.rewardedChan1_SpinBox = QtWidgets.QSpinBox(self.widget)
        self.rewardedChan1_SpinBox.setEnabled(False)
        self.rewardedChan1_SpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.rewardedChan1_SpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.rewardedChan1_SpinBox.setObjectName("rewardedChan1_SpinBox")
        self.gridLayout_10.addWidget(self.rewardedChan1_SpinBox, 3, 0, 1, 1)
        self.rewardedChan7_SpinBox = QtWidgets.QSpinBox(self.widget)
        self.rewardedChan7_SpinBox.setEnabled(False)
        self.rewardedChan7_SpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.rewardedChan7_SpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.rewardedChan7_SpinBox.setObjectName("rewardedChan7_SpinBox")
        self.gridLayout_10.addWidget(self.rewardedChan7_SpinBox, 3, 6, 1, 1)
        self.rewardedChan6_SpinBox = QtWidgets.QSpinBox(self.widget)
        self.rewardedChan6_SpinBox.setEnabled(False)
        self.rewardedChan6_SpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.rewardedChan6_SpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.rewardedChan6_SpinBox.setObjectName("rewardedChan6_SpinBox")
        self.gridLayout_10.addWidget(self.rewardedChan6_SpinBox, 3, 5, 1, 1)
        self.rewardedChan8_SpinBox = QtWidgets.QSpinBox(self.widget)
        self.rewardedChan8_SpinBox.setEnabled(False)
        self.rewardedChan8_SpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.rewardedChan8_SpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.rewardedChan8_SpinBox.setObjectName("rewardedChan8_SpinBox")
        self.gridLayout_10.addWidget(self.rewardedChan8_SpinBox, 3, 7, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_10)
        self.gridLayout_3.addWidget(self.widget, 4, 1, 1, 1)
        self.horizontalLayout_22.addLayout(self.gridLayout_3)
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.horizontalLayout_22.addLayout(self.gridLayout_9)
        self.verticalLayout.addWidget(self.groupBox_5)
        self.saveAsPreset_Button = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.saveAsPreset_Button.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.saveAsPreset_Button.setObjectName("saveAsPreset_Button")
        self.verticalLayout.addWidget(self.saveAsPreset_Button)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_7.addWidget(self.scrollArea)
        self.setupTabVerticalLayout.addWidget(self.trial_GroupBox)
        self.verticalLayout_7.addLayout(self.setupTabVerticalLayout)
        self.begin_Button = QtWidgets.QPushButton(self.setupTab)
        self.begin_Button.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.begin_Button.setObjectName("begin_Button")
        self.verticalLayout_7.addWidget(self.begin_Button)
        self.setDefaults_Button = QtWidgets.QPushButton(self.setupTab)
        self.setDefaults_Button.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.setDefaults_Button.setObjectName("setDefaults_Button")
        self.verticalLayout_7.addWidget(self.setDefaults_Button)
        self.tabWidget.addTab(self.setupTab, "")
        self.liveTab = QtWidgets.QWidget()
        self.liveTab.setObjectName("liveTab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.liveTab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.liveTab)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.liveTabVerticalLayout = QtWidgets.QVBoxLayout()
        self.liveTabVerticalLayout.setObjectName("liveTabVerticalLayout")
        self.sessionTimer_label = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.sessionTimer_label.setFont(font)
        self.sessionTimer_label.setStyleSheet("font-size: 18pt; font-weight: bold;")
        self.sessionTimer_label.setAlignment(QtCore.Qt.AlignCenter)
        self.sessionTimer_label.setObjectName("sessionTimer_label")
        self.liveTabVerticalLayout.addWidget(self.sessionTimer_label)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_17 = QtWidgets.QLabel(self.groupBox)
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_11.addWidget(self.label_17)
        self.trialNum_label = QtWidgets.QLabel(self.groupBox)
        self.trialNum_label.setObjectName("trialNum_label")
        self.horizontalLayout_11.addWidget(self.trialNum_label)
        self.liveTabVerticalLayout.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.sessionPause_pushButton = QtWidgets.QPushButton(self.groupBox)
        self.sessionPause_pushButton.setObjectName("sessionPause_pushButton")
        self.horizontalLayout_20.addWidget(self.sessionPause_pushButton)
        self.sessionAbort_pushButton = QtWidgets.QPushButton(self.groupBox)
        self.sessionAbort_pushButton.setObjectName("sessionAbort_pushButton")
        self.horizontalLayout_20.addWidget(self.sessionAbort_pushButton)
        self.liveTabVerticalLayout.addLayout(self.horizontalLayout_20)
        self.verticalLayout_4.addLayout(self.liveTabVerticalLayout)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBox_4 = QtWidgets.QGroupBox(self.liveTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.preTrialResponseVerticalLayout = QtWidgets.QVBoxLayout()
        self.preTrialResponseVerticalLayout.setContentsMargins(-1, 0, -1, 0)
        self.preTrialResponseVerticalLayout.setObjectName("preTrialResponseVerticalLayout")
        self.verticalLayout_6.addLayout(self.preTrialResponseVerticalLayout)
        self.resultsFigsHorizontalLayout = QtWidgets.QHBoxLayout()
        self.resultsFigsHorizontalLayout.setContentsMargins(-1, 0, -1, 0)
        self.resultsFigsHorizontalLayout.setObjectName("resultsFigsHorizontalLayout")
        self.verticalLayout_6.addLayout(self.resultsFigsHorizontalLayout)
        self.verticalLayout_2.addWidget(self.groupBox_4)
        self.groupBox_2 = QtWidgets.QGroupBox(self.liveTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.sessionFeed_textEdit = QtWidgets.QTextEdit(self.groupBox_2)
        self.sessionFeed_textEdit.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.sessionFeed_textEdit.sizePolicy().hasHeightForWidth())
        self.sessionFeed_textEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(9)
        self.sessionFeed_textEdit.setFont(font)
        self.sessionFeed_textEdit.setStyleSheet("font-family: \"Courier New\";")
        self.sessionFeed_textEdit.setAutoFormatting(QtWidgets.QTextEdit.AutoBulletList)
        self.sessionFeed_textEdit.setReadOnly(True)
        self.sessionFeed_textEdit.setObjectName("sessionFeed_textEdit")
        self.horizontalLayout_15.addWidget(self.sessionFeed_textEdit)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.tabWidget.addTab(self.liveTab, "")
        self.verticalLayout_8.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 758, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.actionFile = QtWidgets.QAction(MainWindow)
        self.actionFile.setObjectName("actionFile")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionUs = QtWidgets.QAction(MainWindow)
        self.actionUs.setObjectName("actionUs")
        self.menuFile.addAction(self.actionFile)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuAbout.addAction(self.actionUs)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.witholdBeforeStim_CheckBox.toggled['bool'].connect(self.witholdBeforeStimMin_SpinBox.setEnabled)
        self.witholdBeforeStim_CheckBox.toggled['bool'].connect(self.witholdBeforeStimMax_SpinBox.setEnabled)
        self.punish_CheckBox.toggled['bool'].connect(self.punishType_ComboBox.setEnabled)
        self.punish_CheckBox.toggled['bool'].connect(self.punishLength_SpinBox.setEnabled)
        self.autoTransition_CheckBox.toggled['bool'].connect(self.autoTransitionTo_ComboBox.setEnabled)
        self.autoTransition_CheckBox.toggled['bool'].connect(self.autoTransitionAfterNum_SpinBox.setEnabled)
        self.autoTransition_CheckBox.toggled['bool'].connect(self.autoTransitionAfterCriteria_ComboBox.setEnabled)
        self.autoReward_CheckBox.toggled['bool'].connect(self.autoRewardDelay_SpinBox.setEnabled)
        self.checkBox.toggled['bool'].connect(self.doubleSpinBox.setEnabled)
        self.checkBox.toggled['bool'].connect(self.spinBox_2.setEnabled)
        self.checkBox.toggled['bool'].connect(self.comboBox.setEnabled)
        self.autoReward_CheckBox.toggled['bool'].connect(self.checkBox.setEnabled)
        self.checkBox.toggled['bool'].connect(self.spinBox.setEnabled)
        self.stim1_CheckBox.toggled['bool'].connect(self.rewardedChan1_SpinBox.setEnabled)
        self.stim1_CheckBox.toggled['bool'].connect(self.respReq1_SpinBox.setEnabled)
        self.stim8_CheckBox.toggled['bool'].connect(self.respReq8_SpinBox.setEnabled)
        self.stim8_CheckBox.toggled['bool'].connect(self.rewardedChan8_SpinBox.setEnabled)
        self.stim7_CheckBox.toggled['bool'].connect(self.respReq7_SpinBox.setEnabled)
        self.stim7_CheckBox.toggled['bool'].connect(self.rewardedChan7_SpinBox.setEnabled)
        self.stim6_CheckBox.toggled['bool'].connect(self.respReq6_SpinBox.setEnabled)
        self.stim6_CheckBox.toggled['bool'].connect(self.rewardedChan6_SpinBox.setEnabled)
        self.stim5_CheckBox.toggled['bool'].connect(self.respReq5_SpinBox.setEnabled)
        self.stim5_CheckBox.toggled['bool'].connect(self.rewardedChan5_SpinBox.setEnabled)
        self.stim4_CheckBox.toggled['bool'].connect(self.respReq4_SpinBox.setEnabled)
        self.stim4_CheckBox.toggled['bool'].connect(self.rewardedChan4_SpinBox.setEnabled)
        self.stim3_CheckBox.toggled['bool'].connect(self.respReq3_SpinBox.setEnabled)
        self.stim3_CheckBox.toggled['bool'].connect(self.rewardedChan3_SpinBox.setEnabled)
        self.stim2_CheckBox.toggled['bool'].connect(self.respReq2_SpinBox.setEnabled)
        self.stim2_CheckBox.toggled['bool'].connect(self.rewardedChan2_SpinBox.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.subjectID_LineEdit, self.weight_SpinBox)
        MainWindow.setTabOrder(self.weight_SpinBox, self.sessionDuration_SpinBox)
        MainWindow.setTabOrder(self.sessionDuration_SpinBox, self.sessionDurationMode_ComboBox)
        MainWindow.setTabOrder(self.sessionDurationMode_ComboBox, self.loadPreset_ComboBox)
        MainWindow.setTabOrder(self.loadPreset_ComboBox, self.device_ComboBox)
        MainWindow.setTabOrder(self.device_ComboBox, self.baudRate_ComboBox)
        MainWindow.setTabOrder(self.baudRate_ComboBox, self.testStim_Button)
        MainWindow.setTabOrder(self.testStim_Button, self.testStimNum_SpinBox)
        MainWindow.setTabOrder(self.testStimNum_SpinBox, self.testReward_Button)
        MainWindow.setTabOrder(self.testReward_Button, self.testRewardNum_SpinBox)
        MainWindow.setTabOrder(self.testRewardNum_SpinBox, self.checkBox_3)
        MainWindow.setTabOrder(self.checkBox_3, self.doubleSpinBox_2)
        MainWindow.setTabOrder(self.doubleSpinBox_2, self.witholdBeforeStim_CheckBox)
        MainWindow.setTabOrder(self.witholdBeforeStim_CheckBox, self.witholdBeforeStimMin_SpinBox)
        MainWindow.setTabOrder(self.witholdBeforeStimMin_SpinBox, self.witholdBeforeStimMax_SpinBox)
        MainWindow.setTabOrder(self.witholdBeforeStimMax_SpinBox, self.response1_CheckBox)
        MainWindow.setTabOrder(self.response1_CheckBox, self.response2_CheckBox)
        MainWindow.setTabOrder(self.response2_CheckBox, self.response3_CheckBox)
        MainWindow.setTabOrder(self.response3_CheckBox, self.reward1_CheckBox)
        MainWindow.setTabOrder(self.reward1_CheckBox, self.reward2_CheckBox)
        MainWindow.setTabOrder(self.reward2_CheckBox, self.checkBox_2)
        MainWindow.setTabOrder(self.checkBox_2, self.stim1_CheckBox)
        MainWindow.setTabOrder(self.stim1_CheckBox, self.respReq1_SpinBox)
        MainWindow.setTabOrder(self.respReq1_SpinBox, self.rewardedChan1_SpinBox)
        MainWindow.setTabOrder(self.rewardedChan1_SpinBox, self.stim2_CheckBox)
        MainWindow.setTabOrder(self.stim2_CheckBox, self.respReq2_SpinBox)
        MainWindow.setTabOrder(self.respReq2_SpinBox, self.rewardedChan2_SpinBox)
        MainWindow.setTabOrder(self.rewardedChan2_SpinBox, self.stim3_CheckBox)
        MainWindow.setTabOrder(self.stim3_CheckBox, self.respReq3_SpinBox)
        MainWindow.setTabOrder(self.respReq3_SpinBox, self.rewardedChan3_SpinBox)
        MainWindow.setTabOrder(self.rewardedChan3_SpinBox, self.stim4_CheckBox)
        MainWindow.setTabOrder(self.stim4_CheckBox, self.respReq4_SpinBox)
        MainWindow.setTabOrder(self.respReq4_SpinBox, self.rewardedChan4_SpinBox)
        MainWindow.setTabOrder(self.rewardedChan4_SpinBox, self.stim5_CheckBox)
        MainWindow.setTabOrder(self.stim5_CheckBox, self.respReq5_SpinBox)
        MainWindow.setTabOrder(self.respReq5_SpinBox, self.rewardedChan5_SpinBox)
        MainWindow.setTabOrder(self.rewardedChan5_SpinBox, self.stim6_CheckBox)
        MainWindow.setTabOrder(self.stim6_CheckBox, self.respReq6_SpinBox)
        MainWindow.setTabOrder(self.respReq6_SpinBox, self.rewardedChan6_SpinBox)
        MainWindow.setTabOrder(self.rewardedChan6_SpinBox, self.stim7_CheckBox)
        MainWindow.setTabOrder(self.stim7_CheckBox, self.respReq7_SpinBox)
        MainWindow.setTabOrder(self.respReq7_SpinBox, self.rewardedChan7_SpinBox)
        MainWindow.setTabOrder(self.rewardedChan7_SpinBox, self.stim8_CheckBox)
        MainWindow.setTabOrder(self.stim8_CheckBox, self.respReq8_SpinBox)
        MainWindow.setTabOrder(self.respReq8_SpinBox, self.rewardedChan8_SpinBox)
        MainWindow.setTabOrder(self.rewardedChan8_SpinBox, self.rewardRemoval_checkBox)
        MainWindow.setTabOrder(self.rewardRemoval_checkBox, self.rewardRemovalDelay_SpinBox)
        MainWindow.setTabOrder(self.rewardRemovalDelay_SpinBox, self.stimOrder_ComboBox)
        MainWindow.setTabOrder(self.stimOrder_ComboBox, self.stimOrderGroupSize_SpinBox)
        MainWindow.setTabOrder(self.stimOrderGroupSize_SpinBox, self.firstStim_ComboBox)
        MainWindow.setTabOrder(self.firstStim_ComboBox, self.repeatIfIncorrect_CheckBox)
        MainWindow.setTabOrder(self.repeatIfIncorrect_CheckBox, self.autoTransition_CheckBox)
        MainWindow.setTabOrder(self.autoTransition_CheckBox, self.autoTransitionTo_ComboBox)
        MainWindow.setTabOrder(self.autoTransitionTo_ComboBox, self.autoTransitionAfterNum_SpinBox)
        MainWindow.setTabOrder(self.autoTransitionAfterNum_SpinBox, self.autoTransitionAfterCriteria_ComboBox)
        MainWindow.setTabOrder(self.autoTransitionAfterCriteria_ComboBox, self.autoTransitionFor_SpinBox)
        MainWindow.setTabOrder(self.autoTransitionFor_SpinBox, self.cueTrial_CheckBox)
        MainWindow.setTabOrder(self.cueTrial_CheckBox, self.cueStim_CheckBox)
        MainWindow.setTabOrder(self.cueStim_CheckBox, self.cueResponse_CheckBox)
        MainWindow.setTabOrder(self.cueResponse_CheckBox, self.cueToStimDelay_SpinBox)
        MainWindow.setTabOrder(self.cueToStimDelay_SpinBox, self.stimLength_SpinBox)
        MainWindow.setTabOrder(self.stimLength_SpinBox, self.respStopsStim_CheckBox)
        MainWindow.setTabOrder(self.respStopsStim_CheckBox, self.postStimDelay_SpinBox)
        MainWindow.setTabOrder(self.postStimDelay_SpinBox, self.responseWindow_SpinBox)
        MainWindow.setTabOrder(self.responseWindow_SpinBox, self.endOfTrialDelay_SpinBox)
        MainWindow.setTabOrder(self.endOfTrialDelay_SpinBox, self.autoReward_CheckBox)
        MainWindow.setTabOrder(self.autoReward_CheckBox, self.autoRewardDelay_SpinBox)
        MainWindow.setTabOrder(self.autoRewardDelay_SpinBox, self.checkBox)
        MainWindow.setTabOrder(self.checkBox, self.doubleSpinBox)
        MainWindow.setTabOrder(self.doubleSpinBox, self.spinBox_2)
        MainWindow.setTabOrder(self.spinBox_2, self.comboBox)
        MainWindow.setTabOrder(self.comboBox, self.spinBox)
        MainWindow.setTabOrder(self.spinBox, self.punish_CheckBox)
        MainWindow.setTabOrder(self.punish_CheckBox, self.punishType_ComboBox)
        MainWindow.setTabOrder(self.punishType_ComboBox, self.punishLength_SpinBox)
        MainWindow.setTabOrder(self.punishLength_SpinBox, self.saveAsPreset_Button)
        MainWindow.setTabOrder(self.saveAsPreset_Button, self.begin_Button)
        MainWindow.setTabOrder(self.begin_Button, self.setDefaults_Button)
        MainWindow.setTabOrder(self.setDefaults_Button, self.tabWidget)
        MainWindow.setTabOrder(self.tabWidget, self.sessionAbort_pushButton)
        MainWindow.setTabOrder(self.sessionAbort_pushButton, self.scrollArea)
        MainWindow.setTabOrder(self.scrollArea, self.sessionPause_pushButton)
        MainWindow.setTabOrder(self.sessionPause_pushButton, self.sessionFeed_textEdit)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "pyBehaviour"))
        self.arduino_GroupBox.setTitle(_translate("MainWindow", "Arduino"))
        self.baudRate_ComboBox.setItemText(0, _translate("MainWindow", "19200"))
        self.baudRateLabel.setText(_translate("MainWindow", "Baud rate"))
        self.deviceLabel.setText(_translate("MainWindow", "Device"))
        self.arduinoConnectedText_Label.setText(_translate("MainWindow", "Not connected"))
        self.testReward_Button.setText(_translate("MainWindow", "Test Reward"))
        self.testStim_Button.setText(_translate("MainWindow", "Test Stim"))
        self.session_GroupBox.setTitle(_translate("MainWindow", "Session"))
        self.numberOfTrialsLabel.setText(_translate("MainWindow", "Duration"))
        self.weightLabel.setText(_translate("MainWindow", "Weight"))
        self.mouseIDLabel.setText(_translate("MainWindow", "Subject ID"))
        self.loadPreset_ComboBox.setItemText(0, _translate("MainWindow", "No configs found"))
        self.loadPresetLabel.setText(_translate("MainWindow", "Load preset"))
        self.sessionDurationMode_ComboBox.setItemText(0, _translate("MainWindow", "Trials"))
        self.sessionDurationMode_ComboBox.setItemText(1, _translate("MainWindow", "Minutes"))
        self.trial_GroupBox.setTitle(_translate("MainWindow", "Advanced"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Trial initiation"))
        self.label_11.setText(_translate("MainWindow", "Active initiation"))
        self.doubleSpinBox_2.setPrefix(_translate("MainWindow", "Response: "))
        self.label_2.setText(_translate("MainWindow", "Withold before stim"))
        self.witholdBeforeStimMin_SpinBox.setPrefix(_translate("MainWindow", "Min: "))
        self.witholdBeforeStimMin_SpinBox.setSuffix(_translate("MainWindow", " s"))
        self.witholdBeforeStimMax_SpinBox.setPrefix(_translate("MainWindow", "Max: "))
        self.witholdBeforeStimMax_SpinBox.setSuffix(_translate("MainWindow", " s"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Stimuli and responses"))
        self.label_16.setText(_translate("MainWindow", "Reward removal"))
        self.reportChannelsLabel.setText(_translate("MainWindow", "Response channels"))
        self.stimLength_SpinBox.setSuffix(_translate("MainWindow", " s"))
        self.respStopsStim_CheckBox.setText(_translate("MainWindow", "Response stops stim"))
        self.autoRewardDelay_SpinBox.setPrefix(_translate("MainWindow", "Delay: "))
        self.label_14.setText(_translate("MainWindow", "End of trial delay"))
        self.rewardRemovalDelay_SpinBox.setPrefix(_translate("MainWindow", "After: "))
        self.rewardRemovalDelay_SpinBox.setSuffix(_translate("MainWindow", " s"))
        self.stimOrderLabel.setText(_translate("MainWindow", "Stim order"))
        self.label_3.setText(_translate("MainWindow", "Cue to stim delay"))
        self.cueToStimDelay_SpinBox.setSuffix(_translate("MainWindow", " s"))
        self.cueTrial_CheckBox.setText(_translate("MainWindow", "Trial"))
        self.cueStim_CheckBox.setText(_translate("MainWindow", "Stim"))
        self.cueResponse_CheckBox.setText(_translate("MainWindow", "Response"))
        self.response1_CheckBox.setText(_translate("MainWindow", "1"))
        self.response2_CheckBox.setText(_translate("MainWindow", "2"))
        self.response3_CheckBox.setText(_translate("MainWindow", "3"))
        self.firstStimLabel.setText(_translate("MainWindow", "First stim"))
        self.stimOrder_ComboBox.setItemText(0, _translate("MainWindow", "Random"))
        self.stimOrder_ComboBox.setItemText(1, _translate("MainWindow", "Interleaved"))
        self.stimOrder_ComboBox.setItemText(2, _translate("MainWindow", "Repeating"))
        self.stimOrderGroupSize_SpinBox.setPrefix(_translate("MainWindow", "Number repeats: "))
        self.label_15.setText(_translate("MainWindow", "Auto reward transition"))
        self.label_7.setText(_translate("MainWindow", "Auto reward"))
        self.endOfTrialDelay_SpinBox.setSuffix(_translate("MainWindow", " s"))
        self.postStimDelay_SpinBox.setSuffix(_translate("MainWindow", " s"))
        self.label_5.setText(_translate("MainWindow", "Post stim delay"))
        self.label_4.setText(_translate("MainWindow", "Stim length"))
        self.label_20.setText(_translate("MainWindow", "Reward channels"))
        self.label_6.setText(_translate("MainWindow", "Response window"))
        self.firstStim_ComboBox.setItemText(0, _translate("MainWindow", "Random"))
        self.label_9.setText(_translate("MainWindow", "Repeat if incorrect"))
        self.doubleSpinBox.setPrefix(_translate("MainWindow", "By: "))
        self.doubleSpinBox.setSuffix(_translate("MainWindow", " s"))
        self.spinBox_2.setPrefix(_translate("MainWindow", "After: "))
        self.comboBox.setItemText(0, _translate("MainWindow", "Performance"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Trials"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Correct trials"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Minutes"))
        self.spinBox.setSuffix(_translate("MainWindow", " min"))
        self.spinBox.setPrefix(_translate("MainWindow", "For: "))
        self.responseWindow_SpinBox.setSuffix(_translate("MainWindow", " s"))
        self.label_8.setText(_translate("MainWindow", "Punish"))
        self.label_10.setText(_translate("MainWindow", "Auto transition config"))
        self.label.setText(_translate("MainWindow", "Cues"))
        self.label_12.setText(_translate("MainWindow", "Stim channels"))
        self.label_13.setText(_translate("MainWindow", "Rewarded channel"))
        self.label_18.setText(_translate("MainWindow", "Response required"))
        self.punishType_ComboBox.setItemText(0, _translate("MainWindow", "Delay"))
        self.punishType_ComboBox.setItemText(1, _translate("MainWindow", "Trigger"))
        self.punishLength_SpinBox.setPrefix(_translate("MainWindow", "Length: "))
        self.punishLength_SpinBox.setSuffix(_translate("MainWindow", " s"))
        self.reward1_CheckBox.setText(_translate("MainWindow", "1"))
        self.reward2_CheckBox.setText(_translate("MainWindow", "2"))
        self.checkBox_2.setText(_translate("MainWindow", "3"))
        self.autoTransitionTo_ComboBox.setItemText(0, _translate("MainWindow", "Browse..."))
        self.autoTransitionAfterNum_SpinBox.setPrefix(_translate("MainWindow", "After: "))
        self.autoTransitionAfterCriteria_ComboBox.setItemText(0, _translate("MainWindow", "Performance"))
        self.autoTransitionAfterCriteria_ComboBox.setItemText(1, _translate("MainWindow", "Trials"))
        self.autoTransitionAfterCriteria_ComboBox.setItemText(2, _translate("MainWindow", "Correct trials"))
        self.autoTransitionAfterCriteria_ComboBox.setItemText(3, _translate("MainWindow", "Minutes"))
        self.autoTransitionFor_SpinBox.setSuffix(_translate("MainWindow", " min"))
        self.autoTransitionFor_SpinBox.setPrefix(_translate("MainWindow", "For: "))
        self.respReq8_SpinBox.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt;\">0: No response</span></p><p><span style=\" font-size:9pt;\">1: Choice 1</span></p><p><span style=\" font-size:9pt;\">2: Choice 2</span></p><p><span style=\" font-size:9pt;\">3: Lick</span></p></body></html>"))
        self.respReq4_SpinBox.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt;\">0: No response</span></p><p><span style=\" font-size:9pt;\">1: Choice 1</span></p><p><span style=\" font-size:9pt;\">2: Choice 2</span></p><p><span style=\" font-size:9pt;\">3: Lick</span></p></body></html>"))
        self.respReq5_SpinBox.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt;\">0: No response</span></p><p><span style=\" font-size:9pt;\">1: Choice 1</span></p><p><span style=\" font-size:9pt;\">2: Choice 2</span></p><p><span style=\" font-size:9pt;\">3: Lick</span></p></body></html>"))
        self.stim2_CheckBox.setText(_translate("MainWindow", "2"))
        self.respReq3_SpinBox.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt;\">0: No response</span></p><p><span style=\" font-size:9pt;\">1: Choice 1</span></p><p><span style=\" font-size:9pt;\">2: Choice 2</span></p><p><span style=\" font-size:9pt;\">3: Lick</span></p></body></html>"))
        self.stim8_CheckBox.setText(_translate("MainWindow", "8"))
        self.stim3_CheckBox.setText(_translate("MainWindow", "3"))
        self.stim6_CheckBox.setText(_translate("MainWindow", "6"))
        self.stim1_CheckBox.setText(_translate("MainWindow", "1"))
        self.stim4_CheckBox.setText(_translate("MainWindow", "4"))
        self.respReq2_SpinBox.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt;\">0: No response</span></p><p><span style=\" font-size:9pt;\">1: Choice 1</span></p><p><span style=\" font-size:9pt;\">2: Choice 2</span></p><p><span style=\" font-size:9pt;\">3: Lick</span></p></body></html>"))
        self.stim7_CheckBox.setText(_translate("MainWindow", "7"))
        self.respReq7_SpinBox.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt;\">0: No response</span></p><p><span style=\" font-size:9pt;\">1: Choice 1</span></p><p><span style=\" font-size:9pt;\">2: Choice 2</span></p><p><span style=\" font-size:9pt;\">3: Lick</span></p></body></html>"))
        self.stim5_CheckBox.setText(_translate("MainWindow", "5"))
        self.respReq6_SpinBox.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt;\">0: No response</span></p><p><span style=\" font-size:9pt;\">1: Choice 1</span></p><p><span style=\" font-size:9pt;\">2: Choice 2</span></p><p><span style=\" font-size:9pt;\">3: Lick</span></p></body></html>"))
        self.respReq1_SpinBox.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt;\">0: No response</span></p><p><span style=\" font-size:9pt;\">1: Choice 1</span></p><p><span style=\" font-size:9pt;\">2: Choice 2</span></p><p><span style=\" font-size:9pt;\">3: Lick</span></p></body></html>"))
        self.saveAsPreset_Button.setText(_translate("MainWindow", "Save as preset..."))
        self.begin_Button.setText(_translate("MainWindow", "Begin"))
        self.setDefaults_Button.setText(_translate("MainWindow", "Set defaults"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.setupTab), _translate("MainWindow", "Setup"))
        self.groupBox.setTitle(_translate("MainWindow", "Session control"))
        self.sessionTimer_label.setText(_translate("MainWindow", "0:00:00"))
        self.label_17.setText(_translate("MainWindow", "Trial:"))
        self.trialNum_label.setText(_translate("MainWindow", "0"))
        self.sessionPause_pushButton.setText(_translate("MainWindow", "Pause"))
        self.sessionAbort_pushButton.setText(_translate("MainWindow", "Abort"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Results"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Communication"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.liveTab), _translate("MainWindow", "Live"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.actionFile.setText(_translate("MainWindow", "New"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionUs.setText(_translate("MainWindow", "Us"))

